### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nathan-08**
Change solution code to use spread operator instead of slice-copy method.

### CODE REVIEW

**Comment by tylercollier-devmtn** [comment]
I prefer the code as it was, for day 1. It's more clear what it's doing. I like to show the spread operator as a shortcut/alternative later. My $0.02.

**Comment by devlemire** [comment]
Yeah you wanna avoid es6 in the early projects. That’s what we found to be more successful in the classroom back when I wrote curriculum full time. Multiple times I had to go back and remove es6 for the more explict way.

**Comment by bethtelford** [comment]
I will bring this to @joeblank attention. In the future I will be better about requiring the mentor to drop the pull in the crew channel for review before merging.

**Comment by joeblank** [comment]
Any thoughts on this from Dallas @jonathanmaydm  or SLC @mciver83 ?

**Pull request merged**
